### ISSUE TITLE
This look promising.

### ISSUE THREAD

**Issue by tsanyqudsi** [candy-kingdom/summary#29]
It's been more than 10 years since I code in C#, and since a year ago I develop a game with my team in Unity. Along the way I managed to find API document generator (the one that currently maintained by dotnet community), but It's hard for me to wrap my head around it.

Sure, it's easy to build and generate, but when I want to customize. The problems starting to appear here and there. I nearly slam my keyboard because of those problems. (exaggerated)

I see this repo might the answer for my team. Unless I understand things wrongly. As I read [your development branch](https://github.com/candy-kingdom/summary/tree/develop), My understanding is that `Summary` will generate a folder of .cs files to something like https://github.com/candy-kingdom/summary/tree/master/docs ? CMIIW.

 I can take the md file generated and put it on a static web generator using nodejs. and even run the script using https://github.com/Elringus/DotNetJS.
 
 I'm very green at the moment with C# but I'm decent with Typescript and web stuff. Do you think it's possible to develop your library in a way that I can make a standard web template with NextJS / ReactJS ? Because from the way I see it now, you did it nicely and doesn't really offer bloated stuff. Which beautiful in my opinion.

**Comment by joshua-light** [comment]
Hi, thanks you for feedback, we really appreciate that!

The initial motivation to build this library was the lack of easy and simple to use API docs generators like `rustdoc` in Rust programming language where the only single action you need to do is to invoke `rustdoc` from the terminal. We want to bring something like that into C# community.

> My understanding is that Summary will generate a folder of .cs files to something like https://github.com/candy-kingdom/summary/tree/master/docs ? CMIIW.

Yes, you absolutely correct! The generator accepts a folder (this can be any folder, even the root of your repository), and it'll then use Roslyn API to parse all the `.cs` files from the folder, convert them into an intermediate representation which will then be rendered as a sequence of `.md` files suitable for hosting in a GitHub, BitBucket or any other web-site that supports static Markdown files hosting. While Markdown files could already be hosted using static-site generator like Hugo or Gatsby, we're planning to implement more sophisticated ways to render docs in future.

> Do you think it's possible to develop your library in a way that I can make a standard web template with NextJS / ReactJS

The library is designed in a way so that you can easily plug in your own renderer instead of the standard Markdown one. To do so, you'll need to write a bit of C#. What you'd need to do is something like this:
```cs
// The folder you want to parse the `*.cs` files from.
const string input = "./src";

// The folder you want to put the generator output into.
const string output = "./docs";

await new SummaryPipeline()
    .UseRoslynParser(input)
    .RenderWith(new CustomRenderPipe())
    .Run();
```

In this way, our Roslyn-based parser will do all the work necessary to extract crucial information from the specific folder but the rendering part (what to do with this information, how to save it on the disk) will be passed into `CustomRenderPipe`.

Here `CustomRenderPipe` can be as simple as:
```cs
public class CustomRenderPipe : IPipe<Doc, Unit>
{
  public Task<Unit> Run(Doc doc)
  {
    // The `doc` object contains all information about types in your project.
    // It also contains documentation for all types, methods, fields, etc.
  }
}
```

(`IPipe<Doc, Unit>` means something like "I'm a function that accepts `Doc` as an input and I don't return any output").

To render Markdown files, we implement our own `Summary.Markdown` plugin that defines [`RenderMarkdownPipe`](https://github.com/candy-kingdom/summary/blob/develop/src/Plugins/Markdown/RenderMarkdownPipe.cs).

**Comment by tsanyqudsi** [comment]
Understood, do you mind if I make somekind of web templating for it? I'm thinking of creating something like `<article>` (since you use `<summary>` and `<article>` will be the web counterpart for putting the .md on the web side)

>  we're planning to implement more sophisticated ways to render docs in future.

I hope it's not like generating web view like the usual documentation generator, the reason why I'm interested with `<summary>` is the focused but not simple goal in parsing C# to Markdown.

The reason why I want to make a separate system for template is because I don't want my repository has two different systems (one for the system itself and the other one is for documentation). This way I can reduce the size of the repo while I can ask others to help me build an internal documentation template from another repository.

An idea but it would be nice if `<summary` is acting as the center of ecosystem whereas there are many libraries / packages / frameworks supporting it.

![image](https://github.com/candy-kingdom/summary/assets/1050880/2940e904-0f82-46ae-bb11-e382cc7b25c4)

I like the approach of Rust / Node / Zig that "lego blocks". C# has Nuget and I think it's nice.

I like your approach in choosing a folder instead of `.csproj` or `.sln` although I haven't test it with my Unity repository. However, I wonder if I can suggest few more things (if not applicable yet) :

- Can I put the source as an array ? for example `['./src', './libs', './utils']`.
- base url ( default is `./` ), so let say I have Unity repo and I want to create the documentation for my Unity repo and the source can be array, I don't want to write `['./Assets/System', './Assets/World', './Assets/Libs']`.
- Display private variables and method for the sake of listing every aspect of the class.
it would be nice if it's part of the core pipeline but optional, something like :

```csharp
await new SummaryPipeline()
    .UseRoslynParser(input)
    .IncludePrivate()
    .RenderWith(new CustomRenderPipe())
    .Run();
```

or if you're nice enough, it can also be created as example/tutorial of creating custom plugin and use it like this :

```csharp
await new SummaryPipeline()
    .UseRoslynParser(input)
    .RenderWith(new CustomRenderPipe())
    .Run();
```
```csharp
public class CustomRenderPipe : IPipe<Doc, Unit>
{
  public Task<Unit> Run(Doc doc)
  {
    IncludePrivate(doc)
    // The `doc` object contains all information about types in your project.
    // It also contains documentation for all types, methods, fields, etc.
  }
}
```

**Comment by joshua-light** [comment]
> An idea but it would be nice if <summary is acting as the center of ecosystem whereas there are many libraries / packages / frameworks supporting it.

That's something we had in mind building `<summary>` as a very modular project. We implemented a pipe-based approach where all flow of the program consists of carefully designed and composed pipes that act as simple functions passing data through. Thus we see `<summary>` architecture as this:
- `Summary`: the core package that contains all base types for almost everything
- `Summary.Roslyn`: the parser (there are other strategies from Roslyn to parse docs, e.g., using XML-generated files, but we think they're not as flexible, so we focus only on Roslyn at the moment)
- `Summary.Markdown`: the renderer (here, also, could be a set of alternatives for any case and users can even roll their own `Summary.Gatsby` or something renderer that will be specifically tuned for Gatsby static-site generator, etc.)
- `Summary.*`: anything that can be built on top of any package can also be a separate package allowing for full flexibility for end user.

In this way, users can build their own generator as in LEGO constructor. Additionally, we're also planning to provide a convenient CLI that can be installed as a dotnet tool to make things even easier in the average case.

Regarding suggestions:
> Can I put the source as an array ? for example ['./src', './libs', './utils'].

I added a ticket for that. Thanks, it's a nice idea!

> base url ( default is ./ ), so let say I have Unity repo and I want to create the documentation for my Unity repo and the source can be array, I don't want to write ['./Assets/System', './Assets/World', './Assets/Libs'].

If I understand you correctly, having this feature, you'd be able to specify base path as `./Assets` so that directories can be passed as an array of `["./System", "./World", "./Libs"]`?

> Display private variables and method for the sake of listing every aspect of the class.
it would be nice if it's part of the core pipeline but optional, something like

I also added a ticket for this case, thanks! Currently, we filter out private members using `FilterPublicMembersPipe` but we can easily make this behavior configurable by the end user.

**Comment by tsanyqudsi** [comment]
> If I understand you correctly, having this feature, you'd be able to specify base path as ./Assets so that directories can be passed as an array of ["./System", "./World", "./Libs"]?

Exactly. I took the inspiration from [here](https://www.typescriptlang.org/tsconfig#baseUrl).

---

I was thinking of giving a suggestion about -watch flag so `<summary>` would generate the MD whenever the file content change. But seeing #24, I think it would be better if it embeds to the plugin of an IDE where the plugin will check if the content of the file changed and then generate the markdown if it does.

**Why**
Many people nowadays using IDE such as Rider, VSCode, and VS for building C# programs. While there are few others that will build it using neovim / vim due to their preference, but it's hardly found since the nature of C# was made for Windows at first. 

I will try to make an extension for VSCode for summary, will do a pull request here if you want the extension to be included in this repo.

---

I made [`<article />`](https://github.com/tsanyqudsi/article) a NextJS based web templating for `<summary>`. It's still an Initial commit of sorts, so wish me luck.

the idea of the project is:
- Build a separate repo for the documentation web interface so the people that want to contribute for the functionality and the design of the template doesn't have to clone the whole source code of the program just to edit the documentation template.
- Separate the layer for documentation. Sometimes the source code is private, and you have outside collaborators that you want to help build the documentation look and feels. Using the current solutions, you can't do that.
- Additional auth layer for the documentation. In the future, I want to add some kind of role-based auth so people can limit who can read the documentation and which part of the documentation should be able to be read.
- Table of Contents (some kind of Index.md) but I noticed that you're trying to make it reality in #21 so I figured I'll just wait and use that instead.

**Comment by joshua-light** [comment]
> I was thinking of giving a suggestion about -watch flag so <summary> would generate the MD whenever the file content change. But seeing https://github.com/candy-kingdom/summary/issues/24, I think it would be better if it embeds to the plugin of an IDE where the plugin will check if the content of the file changed and then generate the markdown if it does.

That seems reasonable. At first, I had an idea that initially it'd be easier to integrate `summary` using simple CI/CD pipeline but now I think that both `-watch` flag and separate plugin that automatically regenerates everything is quite good since then you could run the generator and forget about it: just add new files/edit existing ones and commit both source files and documentation automatically into the same repository.

> Table of Contents (some kind of Index.md) but I noticed that you're trying to make it reality in https://github.com/candy-kingdom/summary/issues/21 so I figured I'll just wait and use that instead.

Feel free to suggest any ideas you have in mind, your contribution is very appreciated!

**Comment by tsanyqudsi** [comment]
I do have few more, but I'll close this one since it's better to make new focused issues instead.
